投稿メモの保存機能の作成
Kousuke-N/restaurant_memo pull request #10
Opened 2018-01-04 11:14 UTC by shikibu9419

close #9 

+        val placeId = "place id"

2018-01-04 13:30 UTC, Kousuke-N requested changes
一部修正お願い

2018-01-04 13:30 UTC, Kousuke-N commented on app/src/main/java/com/example/product/restaurantmemo/ShopLog.kt
> +        open var id: Long = 1,
ここ1っておいて大丈夫？

2018-01-04 13:30 UTC, Kousuke-N commented on app/src/main/res/layout/activity_post.xml
> +        android:id="@+id/post_appearance"
ここらへん俺が悪かったけどこのissueですべきじゃなかったな..
今回は修正必要ないです

2018-01-04 13:30 UTC, Kousuke-N commented on app/src/main/java/com/example/product/restaurantmemo/PostActivity.kt
> +        super.onDestroy()
superは一番最後の方がいい(destroyの場合)

2018-01-04 13:30 UTC, Kousuke-N commented on app/src/main/java/com/example/product/restaurantmemo/PostActivity.kt
> +        if(!realm.isEmpty) {
ifの下の処理はこの中に書いたほうがいいのでは？

2018-01-04 14:15 UTC, shikibu9419 commented on app/src/main/java/com/example/product/restaurantmemo/ShopLog.kt
> +        open var id: Long = 1,
1番最初のidをなんとなく1とおいてたな...
id: Long = 0 に変更します

2018-01-04 14:16 UTC, shikibu9419 commented on app/src/main/res/layout/activity_post.xml
> +        android:id="@+id/post_appearance"
勝手に進めた僕も悪いので...

2018-01-05 00:41 UTC, Kousuke-N requested changes
ここだけ修正でマージしよう

2018-01-05 00:41 UTC, Kousuke-N commented on app/src/main/java/com/example/product/restaurantmemo/PostActivity.kt
> +        realm.executeTransaction {
ここ未対応では？
realmがnullだった時ここで落ちそう

2018-01-05 03:18 UTC, shikibu9419 commented on app/src/main/java/com/example/product/restaurantmemo/PostActivity.kt
> +        realm.executeTransaction {
realmがnullになるパターンってなんだろう...
そこのメソッドを呼ぶ前にgetDefaultInstanceされてるから問題ないと思ったんやけど

2018-01-05 04:10 UTC, Kousuke-N approved these changes

2018-01-05 04:10 UTC, merged