詳細画面の作成
Kousuke-N/restaurant_memo pull request #14
Opened 2018-01-20 08:41 UTC by shikibu9419

close #4 
commitが一緒になってしまってますが、詳細画面の作成と他画面のレイアウトの調整をしました

2018-01-22 13:32 UTC, Kousuke-N requested changes
この修正をお願い
あとコミットの途中にmergeが入ってるのはなぜ…？
なんか変になったときはgit rebase -iでうまいことできたりする
調べてみて～

2018-01-22 13:32 UTC, Kousuke-N commented on app/src/main/java/com/example/product/restaurantmemo/DetailFragment.kt
> +package com.example.product.restaurantmemo
純粋な疑問として聴きたいんやけど、ここはなんでフラグメントたてたん？
理由あり？それともなんとなく？

2018-01-22 13:32 UTC, Kousuke-N commented on app/src/main/java/com/example/product/restaurantmemo/MainActivity.kt
> -        fab.setOnClickListener {
これは必要

2018-01-22 14:03 UTC, shikibu9419 commented on app/src/main/java/com/example/product/restaurantmemo/MainActivity.kt
> -        fab.setOnClickListener {
修正しました(こういうことやんね...?)

2018-01-22 14:10 UTC, shikibu9419 commented on app/src/main/java/com/example/product/restaurantmemo/DetailFragment.kt
> +package com.example.product.restaurantmemo
アクティビティにデータ処理とかをあまり詰め込まない方がいいって聞くから、かなぁ
1つにまとめるとファイルが大きくなりそうだったってのもあるし

2018-01-22 14:18 UTC, Kousuke-N commented on app/src/main/java/com/example/product/restaurantmemo/DetailFragment.kt
> +package com.example.product.restaurantmemo
あ～そゆことね
いや、なんかすごいテクニックが秘められてるのかな？って思った()

2018-01-22 15:18 UTC, shikibu9419 commented on app/src/main/java/com/example/product/restaurantmemo/DetailFragment.kt
> +package com.example.product.restaurantmemo
そういうわけではなかったw

2018-01-23 23:37 UTC, Kousuke-N commented
okです！
LGTM

2018-01-23 23:37 UTC, Kousuke-N approved these changes

2018-01-23 23:37 UTC, merged